#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : enchant
Version  : 1.6.1
Release  : 1
URL      : https://github.com/AbiWord/enchant/releases/download/enchant-1-6-1/enchant-1.6.1.tar.gz
Source0  : https://github.com/AbiWord/enchant/releases/download/enchant-1-6-1/enchant-1.6.1.tar.gz
Summary  : An Enchanting Spell Checking Library
Group    : Development/Tools
License  : LGPL-2.1
Requires: enchant-bin
Requires: enchant-lib
Requires: enchant-data
Requires: enchant-doc
BuildRequires : pkgconfig(dbus-glib-1)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(hunspell)

%description
A library that wraps other spell checking backends.

%package bin
Summary: bin components for the enchant package.
Group: Binaries
Requires: enchant-data

%description bin
bin components for the enchant package.


%package data
Summary: data components for the enchant package.
Group: Data

%description data
data components for the enchant package.


%package dev
Summary: dev components for the enchant package.
Group: Development
Requires: enchant-lib
Requires: enchant-bin
Requires: enchant-data
Provides: enchant-devel

%description dev
dev components for the enchant package.


%package doc
Summary: doc components for the enchant package.
Group: Documentation

%description doc
doc components for the enchant package.


%package lib
Summary: lib components for the enchant package.
Group: Libraries
Requires: enchant-data

%description lib
lib components for the enchant package.


%prep
%setup -q -n enchant-1.6.1

%build
export LANG=C
export SOURCE_DATE_EPOCH=1491847021
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1491847021
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/enchant
/usr/bin/enchant-lsmod

%files data
%defattr(-,root,root,-)
/usr/share/enchant/enchant.ordering

%files dev
%defattr(-,root,root,-)
/usr/include/enchant/enchant++.h
/usr/include/enchant/enchant-provider.h
/usr/include/enchant/enchant.h
/usr/lib64/libenchant.so
/usr/lib64/pkgconfig/enchant.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/enchant/libenchant_ispell.so
/usr/lib64/enchant/libenchant_myspell.so
/usr/lib64/enchant/libenchant_zemberek.so
/usr/lib64/libenchant.so.1
/usr/lib64/libenchant.so.1.6.1
